# Generated by Django 3.2.6 on 2024-01-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('poster', models.ImageField(upload_to='category_poster/', verbose_name='Постер')),
                ('url', models.SlugField(max_length=160)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('poster', models.ImageField(upload_to='furni_poster/', verbose_name='Постер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебели',
            },
        ),
        migrations.CreateModel(
            name='AdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('image', models.ImageField(upload_to='additional_furni/', verbose_name='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zell.furniture', verbose_name='')),
            ],
            options={
                'verbose_name': 'Даполнительный изображение',
                'verbose_name_plural': 'Даполнительный изображении',
            },
        ),
    ]
