# Generated by Django 3.2.6 on 2024-01-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zell.category', verbose_name='Категория'),
        ),
    ]
