# Generated by Django 3.2.6 on 2024-01-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zell', '0002_furniture_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalimages',
            old_name='movie',
            new_name='furniture',
        ),
    ]
